version: '3.8'

services:
  # front:
  #   container_name: frontend
  #   build: ./frontend
  #   user: node
  #   volumes:
  #     - ./frontend:/app:cached
  #     - /app/node_modules
  #   ports:
  #     - ${FRONT_PORT}:3000
  #   networks:
  #     - backend

  api:
    container_name: API
    build: ./backend
    user: node
    environment:
      PORT: ${BACK_PORT}
    volumes:
      - ./backend:/app:cached
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1028M

  bd:
    container_name: database
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${BD_PORT}:8080
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: unless-stopped
    networks:
      - backend
volumes:
  db:
    driver: local
networks:
  backend:
    driver: bridge
