version: '3.8'

services:
  # front:
  #   container_name: frontend
  #   build: ./frontend
  #   user: node
  #   volumes:
  #     - ./frontend:/app:cached
  #     - /app/node_modules
  #   ports:
  #     - ${FRONT_PORT}:3000
  #   networks:
  #     - backend

  api:
    container_name: API
    build: ./backend
    user: node
    environment:
      PORT: ${BACK_PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app:cached
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1028M

  bd-mongo:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./volumes/mongodb:/data/db
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge
